//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileProcessor.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileProcessor.Resources.ExceptionMessages", typeof(ExceptionMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field failed to convert {1} from {2} to {3}. See inner exception for details..
        /// </summary>
        public static string ConversionException {
            get {
                return ResourceManager.GetString("ConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field failed to convert {1} from {2} to {3} using the format string {4}. See inner exception for details..
        /// </summary>
        public static string ConversionExceptionWithFormatString {
            get {
                return ResourceManager.GetString("ConversionExceptionWithFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} property requires a {1} to be defined..
        /// </summary>
        public static string FieldAttributeMissing {
            get {
                return ResourceManager.GetString("FieldAttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both the True and False values must be supplied for the Boolean Attribute. Use string.Empty to have a True or False return a blank..
        /// </summary>
        public static string InvalidBooleanAttribute {
            get {
                return ResourceManager.GetString("InvalidBooleanAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid boolean value..
        /// </summary>
        public static string InvalidBooleanValue {
            get {
                return ResourceManager.GetString("InvalidBooleanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid to convert with the {1} format string..
        /// </summary>
        public static string InvalidDateTimeFormat {
            get {
                return ResourceManager.GetString("InvalidDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal separator can only be &apos;.&apos; or &apos;,&apos;..
        /// </summary>
        public static string InvalidDecimalSeparator {
            get {
                return ResourceManager.GetString("InvalidDecimalSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid decimal value..
        /// </summary>
        public static string InvalidDecimalValue {
            get {
                return ResourceManager.GetString("InvalidDecimalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid field alignment..
        /// </summary>
        public static string InvalidFieldAlignment {
            get {
                return ResourceManager.GetString("InvalidFieldAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Converters assigned to a property must implement IFieldConverter.
        /// </summary>
        public static string InvalidFieldConverter {
            get {
                return ResourceManager.GetString("InvalidFieldConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        public static string NullValue {
            get {
                return ResourceManager.GetString("NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is longer than the expected field length..
        /// </summary>
        public static string Overflow {
            get {
                return ResourceManager.GetString("Overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} record requires a {1} to be defined..
        /// </summary>
        public static string RecordAttributeMissing {
            get {
                return ResourceManager.GetString("RecordAttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion for data type of parameter has not been implemented..
        /// </summary>
        public static string UnexpectedDataType {
            get {
                return ResourceManager.GetString("UnexpectedDataType", resourceCulture);
            }
        }
    }
}
